Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "name"
          AttributeType: "S"
        - 
          AttributeName: "cpf"
          AttributeType: "S"          
      KeySchema: 
        - 
          AttributeName: "name"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
       - 
          IndexName: GSI_CPF
          KeySchema: 
            - 
              AttributeName: "cpf"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL 
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "people-table"

Outputs:
  DynamoDBTable:
    Value: !Ref DynamoDBTable
    Export:
      Name: people-table

