Parameters:
  TypeProject:
    Type: String
    Default: people

Resources:
  S3BucketLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${TypeProject}-lambda-s3

Outputs:
  S3BucketLambdaName:
    Value: !Ref S3BucketLambda
    Export:
      Name: !Sub ${TypeProject}-lambda-s3-bucket-name
